import inspect, functools, base64, pickle, math, os, mmap, ctypes, struct
from fcntl import ioctl
from tinygrad.device import Compiled, Allocator, Compiler
from tinygrad.renderer import Renderer, cstyle, nir, ptx, llvmir, wgsl
from tinygrad.dtype import dtypes
from tinygrad.uop.ops import UOp, Ops, PatternMatcher, UPat, AxisType, graph_rewrite
from tinygrad.uop.symbolic import symbolic
from tinygrad.helpers import dedup, cpu_profile, DEBUG, getenv

# the structured path: matmul/elementwise are extracted from the uop graph (extract_matmul / extract_elementwise /
# extract_bias_vector) and run via clang/NPU; the leftover loop renders straight to C (compact_loop_to_c). every op the RK
# renderer emits is renderable, so there is no per-uop interpreter fallback -- an unhandled op/dtype raises at compile time.
# the whole NPU stack lives in THIS file with no external module and no numpy: the renderer emits the register-command
# stream (ew_command / gemm_command, mirroring the rknpu hardware), and the runtime (_NPU + _run_npu_ew / _run_npu_gemm)
# only allocates buffers, moves data as raw bytes (struct/memoryview), patches DMA addresses, and submits the ioctl.

# the matmul reductions are pulled out of the graph as a structured GEMM (M,K,N); each extracted GEMM runs on the NPU
# MAC and writes straight to the output buffer C; its result value is replaced by a LOAD back from
# C[m,n] so the epilogue reads it. meta collected here, consumed in render.
_RK_GEMM:list[tuple] = []
# the elementwise epilogue is *also* pulled out structurally (extract_elementwise) -> an EW chain descriptor run on the
# NPU DPU-EW with a clang CPU fallback (ew_lines), or, when it's exactly C+const / C+bias[n], fused into the GEMM.
_RK_EW:list[dict] = []
# a  C[m,n] + bias[n]  epilogue (per-column bias broadcast over rows) is pulled out as a VECTOR fused into the GEMM
# via matmul augmentation ([x|1]@[W;b], pure matmul). collected here per kernel as (out_buf, bias_param, base, stride, N).
_RK_BIAS:list[tuple] = []

# ============================================================================================================
# the NPU runtime, moved into this file (absorbed from /data/rkt gemm.py + chain_add.py) so the RK backend needs no
# numpy and no external module. it is JUST the /dev/dri/card1 ioctl interface: open + mem_allocate + submit + the
# regcmd/task layout. the actual register COMMANDS are generated by the renderer (ew_command / gemm_command); data
# moves as raw bytes (struct/memoryview) -- fp16 buffers pass straight through, fp32 is narrowed with struct('e').
class _mc(ctypes.Structure): _fields_=[("handle",ctypes.c_uint32),("flags",ctypes.c_uint32),("size",ctypes.c_uint64),
                                       ("obj_addr",ctypes.c_uint64),("dma_addr",ctypes.c_uint64),("sram_size",ctypes.c_uint64)]
class _mm(ctypes.Structure): _fields_=[("handle",ctypes.c_uint32),("reserved",ctypes.c_uint32),("offset",ctypes.c_uint64)]
class _act(ctypes.Structure): _fields_=[("flags",ctypes.c_uint32),("value",ctypes.c_uint32)]
class _sc(ctypes.Structure): _fields_=[("task_start",ctypes.c_uint32),("task_number",ctypes.c_uint32)]
class _sb(ctypes.Structure): _fields_=[("flags",ctypes.c_uint32),("timeout",ctypes.c_uint32),("task_start",ctypes.c_uint32),
  ("task_number",ctypes.c_uint32),("task_counter",ctypes.c_uint32),("priority",ctypes.c_int32),("task_obj_addr",ctypes.c_uint64),
  ("iommu_domain_id",ctypes.c_uint32),("reserved",ctypes.c_uint32),("task_base_addr",ctypes.c_uint64),("hw_elapse_time",ctypes.c_int64),
  ("core_mask",ctypes.c_uint32),("fence_fd",ctypes.c_int32),("subcore_task",_sc*5)]
class _tk(ctypes.Structure): _fields_=[("flags",ctypes.c_uint32),("op_idx",ctypes.c_uint32),("enable_mask",ctypes.c_uint32),
  ("int_mask",ctypes.c_uint32),("int_clear",ctypes.c_uint32),("int_status",ctypes.c_uint32),("regcfg_amount",ctypes.c_uint32),
  ("regcfg_offset",ctypes.c_uint32),("regcmd_addr",ctypes.c_uint64)]
_IOWR = lambda t,nr,sz: (3<<30)|(ord(t)<<8)|nr|(sz<<16)
_MEMC,_MEMM,_SUB,_ACT = _IOWR('d',0x42,ctypes.sizeof(_mc)),_IOWR('d',0x43,ctypes.sizeof(_mm)),_IOWR('d',0x41,ctypes.sizeof(_sb)),_IOWR('d',0x40,ctypes.sizeof(_act))

class _NPU:
  def __init__(self):
    self.fd = os.open(getenv("RK_CARD", "/dev/dri/card1"), os.O_RDWR)
    self.task_map, self.task_mc = self.alloc(64*1024, 8)        # task descriptors (KERNEL_MAPPING|NON_CACHEABLE)
    self.regcmd_map, self.regcmd_mc = self.alloc(512*1024, 0)   # register-command stream (NON_CACHEABLE)
    self.tasks = ctypes.cast(ctypes.addressof(ctypes.c_char.from_buffer(self.task_map)), ctypes.POINTER(_tk))
    self.regcmd = ctypes.cast(ctypes.addressof(ctypes.c_char.from_buffer(self.regcmd_map)), ctypes.POINTER(ctypes.c_uint64))
    self.gbufs = None
  def alloc(self, size, flags):                                # MEM_CREATE + MEM_MAP + mmap -> (mmap, mem_create)
    mc = _mc(flags=flags, size=size); ioctl(self.fd, _MEMC, mc)
    mp = _mm(handle=mc.handle); ioctl(self.fd, _MEMM, mp)
    return mmap.mmap(self.fd, mc.size, mmap.MAP_SHARED, mmap.PROT_READ|mmap.PROT_WRITE, offset=mp.offset), mc
  def reset(self): ioctl(self.fd, _ACT, _act(flags=1, value=0))
  def gemm_bufs(self):                                         # resident input/weight/output for the MAC (allocated once)
    if self.gbufs is None:
      b = getenv("RK_GEMM_BUF_MB", 4)*1024*1024; self.gbufs = (self.alloc(b,0), self.alloc(b,0), self.alloc(b,0))
    return self.gbufs
  def write_regs(self, task_regs, op_enable, op_idx_seq, last_nop):
    # lay the per-task register blocks into the regcmd buffer, PC-chain them (each tail re-issues OPERATION_ENABLE and
    # points at the next block; the last ends the chain) and fill the task descriptors. op_enable=0x18 (DPU-EW)/0xd (MAC).
    enable = _E(0x0081, 0x0008, op_enable)                     # E(PC, OPERATION_ENABLE, op_enable)
    offs, off = [], 0
    for regs in task_regs: offs.append(off); off += (len(regs)+4+1)//2*2   # +4 PC-tail qwords, 2-qword aligned
    if off*8 > self.regcmd_mc.size: raise RuntimeError("regcmd buffer too small")
    for i in range(off): self.regcmd[i] = 0
    for idx, regs in enumerate(task_regs):
      base = offs[idx]
      for i, q in enumerate(regs): self.regcmd[base+i] = q
      if idx+1 < len(task_regs):
        na = self.regcmd_mc.dma_addr + offs[idx+1]*8
        tail = [_E(0x0101,0x0010,na & 0xFFFFFFF0), _E(0x0101,0x0014,((len(task_regs[idx+1])+1)//2)+1), _E(0x0041,0,0), enable]
      else: tail = [last_nop, _E(0x0101,0x0014,0), _E(0x0041,0,0), enable]
      for i, q in enumerate(tail): self.regcmd[base+len(regs)+i] = q
      t = self.tasks[idx]
      t.flags, t.op_idx, t.enable_mask = 0, (idx if op_idx_seq else 0), op_enable
      t.int_mask, t.int_clear, t.int_status = 0x300, 0x1ffff, 0
      t.regcfg_amount, t.regcfg_offset, t.regcmd_addr = len(regs), 0, self.regcmd_mc.dma_addr + base*8
  def submit(self, task_count, reset=False):                  # fire the PC-chained tasks (BLOCK -> returns when done)
    if reset: self.reset()
    s = _sb(flags=0x5, timeout=6000, task_number=task_count, task_obj_addr=self.task_mc.obj_addr, core_mask=1, fence_fd=-1)
    s.subcore_task[0], s.subcore_task[1], s.subcore_task[2] = _sc(0,task_count), _sc(task_count,0), _sc(task_count,0)
    return ioctl(self.fd, _SUB, s)

_NPU_DEV = None
def _npu():
  global _NPU_DEV
  if _NPU_DEV is None: _NPU_DEV = _NPU()                       # open /dev/dri/card1 on first NPU use
  return _NPU_DEV

def _f16(vals):
  # list of python floats -> fp16 little-endian bytes. a finite value past the fp16 range -> +-inf (matches numpy narrowing).
  try: return struct.pack(f"<{len(vals)}e", *vals)
  except (OverflowError, struct.error):
    return struct.pack(f"<{len(vals)}e", *(v if -65504.0 <= v <= 65504.0 else math.copysign(math.inf, v) for v in vals))

# the GEMM register command, inlined numpy-free from gemm.py:make_gemm_regs (verified byte-identical). NVDLA 1x1-conv MAC:
# CNA loads the input feature + decompressed weight, CORE does the MAC, DPU writes the (optionally BS-biased) output.
_CD = lambda x, y: (x+y-1)//y                                  # ceil_div
def _gemm_layout(m, n, k):
  au = lambda x, a: _CD(x, a)*a
  aligned_k, align_out = max(32, au(k, 32)), max(32, au(n, 32)); align_in = max(aligned_k, align_out)
  return align_in, align_out, (align_in if align_in != aligned_k else k)
def _make_gemm_regs(m, n, k, in_dma, wt_dma, out_dma, out_fp16=False, bias=None):
  CNA, CORE, DPU = 0x0201, 0x0801, 0x1001
  align_in, align_out, eff_k = _gemm_layout(m, n, k); irb = align_in*2                  # input_row_bytes (fp16)
  out_precision, size_e = (2,1) if out_fp16 else (5,3)
  feature_grains = max(80, (_CD(2*32768, irb)+1) & ~1)                                  # >=80 keeps the CSC->CMAC->CACC pipe fed
  data_banks = max(1, min(_CD(m*irb, 32768), 11)); line_stride = 4*min(_CD(eff_k,32),13); notch = 8*min(align_out//32,13)-1
  regs = [_E(DPU,0x4004,(1<<3)|(1<<2)|(1<<1)), _E(CNA,0x100c,(2<<4)|(2<<7)|(1<<29)), _E(CNA,0x1010,feature_grains<<4),
    _E(CNA,0x1014,(1<<3)|1), _E(CNA,0x1020,(1<<16)|m), _E(CNA,0x1024,((align_in-1)<<16)|align_in), _E(CNA,0x1028,1),
    _E(CNA,0x102c,m), _E(CNA,0x1030,irb*align_out), _E(CNA,0x1034,irb), _E(CNA,0x1038,(1<<24)|(1<<16)|align_out),
    _E(CNA,0x1040,((12-data_banks)<<4)|data_banks), _E(CNA,0x1044,_CD(align_in,32)), _E(CNA,0x104c,(1<<3)|(1<<1)|1),
    _E(CNA,0x1050,1<<16), _E(CNA,0x1054,1<<16), _E(CNA,0x1058,1<<16), _E(CNA,0x105c,1<<16), _E(CNA,0x1070,in_dma),
    _E(CNA,0x1078,(15<<16)|15), _E(CNA,0x107c,line_stride), _E(CNA,0x1080,0), _E(CNA,0x1084,(1<<16)|m), _E(CNA,0x1088,align_in),
    _E(CNA,0x1110,wt_dma), _E(CORE,0x3010,(2<<8)|1), _E(CORE,0x3014,((m-1)<<16)|0), _E(CORE,0x3018,align_out-1),
    _E(CORE,0x3030,0), _E(DPU,0x400c,(15<<5)|(2<<1)), _E(DPU,0x4010,(out_precision<<29)|(2<<26)|2), _E(DPU,0x4020,out_dma),
    _E(DPU,0x4024,1<<4), _E(DPU,0x4030,0), _E(DPU,0x4034,m-1), _E(DPU,0x4038,(notch<<16)|notch),
    _E(DPU,0x403c,((align_out-1)<<16)|(align_out-1)), _E(DPU,0x4040,(1<<6)|(1<<4)|(1<<1)|1),
    _E(DPU,0x4050,(size_e<<8)|(size_e<<5)|(size_e<<2)|(1<<1)), _E(DPU,0x4058,align_out-1), _E(DPU,0x405c,((m-1)<<16)|0),
    _E(DPU,0x4060,(1<<6)|(1<<4)|(1<<1)|1), _E(DPU,0x4070,(1<<9)|(1<<8)|(1<<7)|(1<<1)|1),
    _E(DPU,0x4084,((1<<16)|1) if out_fp16 else 0), _E(DPU,0x40c0,(1*4)<<4)]
  if bias is not None:                                          # un-bypass the DPU BS (X1) ALU for a scalar +bias (fp32 operand)
    bs = [_E(DPU,0x4040,(2<<16)|(1<<6)|(1<<4)), _E(DPU,0x4044,struct.unpack('<I',struct.pack('<f',bias))[0])]
    regs = [r for q in regs for r in (bs if (q & 0xFFFF) == 0x4040 else [q])]
  return regs

def extract_matmul(sink:UOp):
  # find the contraction accumulator loop (kept as a raw M,K,N reduce by structured_reduce). extract M,K,N + the affine
  # A/B/C index maps, then replace the loop's result value with LOAD(C[m,n]); the K loop goes dead and only M,N remain.
  topo = list(sink.toposort())
  kr = [u for u in topo if u.op is Ops.RANGE and u.arg[1] is AxisType.REDUCE]
  if len(kr) != 1: return None                                                       # only single-reduce GEMMs
  K = kr[0]
  prod = [u for u in topo if u.op is Ops.MUL and u.dtype is dtypes.float and all(s.op is Ops.LOAD for s in u.src)]
  if len(prod) != 1: return None                                                     # MUL(LOAD A, LOAD B) is the product
  la, lb = prod[0].src
  ia, ib = la.src[0].src[1], lb.src[0].src[1]                                         # the index expressions into A,B
  rng_of = lambda e: {u for u in e.toposort() if u.op is Ops.RANGE}
  ra, rb = rng_of(ia), rng_of(ib)
  if K not in ra or K not in rb or len(ra) != 2 or len(rb) != 2: return None
  M, N = (ra-{K}).pop(), (rb-{K}).pop()                                               # A indexes (M,K); B indexes (K,N)
  # the GEMM result is the value read out of the accumulator after the K loop (not the in-loop reload)
  res = [u for u in topo if u.op is Ops.LOAD and u.src[0].src[0].op is Ops.AFTER and
         any(s.op is Ops.END and K in s.src for s in u.src[0].src[0].src)]
  if len(res) != 1: return None
  res = res[0]
  # the single output store this result flows into -> gives the output buffer C and its (m,n) index map
  st = [u for u in topo if u.op is Ops.STORE and u.src[0].op is Ops.INDEX and u.src[0].src[0].op is Ops.PARAM and res in u.src[1].toposort()]
  if len(st) != 1: return None
  cidx = st[0].src[0]
  iv = lambda e, vm: graph_rewrite(e.substitute({r: r.const_like(v) for r, v in vm.items()}), symbolic).arg
  ba, bb, cb = iv(ia,{M:0,K:0}), iv(ib,{K:0,N:0}), iv(cidx.src[1],{M:0,N:0})
  am, ak = iv(ia,{M:1,K:0})-ba, iv(ia,{M:0,K:1})-ba
  bk, bn = iv(ib,{K:1,N:0})-bb, iv(ib,{K:0,N:1})-bb
  cm, cn = iv(cidx.src[1],{M:1,N:0})-cb, iv(cidx.src[1],{M:0,N:1})-cb
  pa, pb = la.src[0].src[0], lb.src[0].src[0]                                         # the A,B param uops
  _RK_GEMM.append((M.vmax+1, K.vmax+1, N.vmax+1, pa.arg, pb.arg, ba, am, ak, bb, bk, bn, cidx.src[0].arg, cb, cm, cn))
  out = sink.substitute({res: UOp(Ops.LOAD, res.dtype, (cidx,))})                     # read the gemm output back from C[m,n]
  # A,B no longer have any load after extraction; keep their params reachable (as NOOPs) so they stay in globals
  return out.replace(src=out.src + tuple(UOp(Ops.NOOP, dtypes.void, (p,)) for p in (pa, pb)))

EW_BINOPS = {Ops.ADD:"ADD", Ops.MUL:"MUL", Ops.SUB:"SUB", Ops.FDIV:"DIV"}   # extractable EW binops (must be in ew_lines' EW_C)
NPF = {dtypes.float:"float32", dtypes.half:"float16"}   # float dtypes the NPU EW (chain_add) handles; the descriptor carries one
                                                        # so the runtime reads/writes the buffer & sizes scratch at the right width
# max DPU-EW ops PC-chained into ONE chain_add submit. chain_add grows its regcmd buffer, so this is NOT the old "1KB / 6
# block" toolkit limit -- verified to 256 ops on hardware; capped here, beyond it the chain renders as a CPU C loop. (an
# NPU mem/submit failure for a long chain still falls back to clang, so the cap is a perf knob, not a correctness one.)
EW_MAX_OPS = 64

# --- the NPU DPU-EW register command, generated HERE in the renderer (mirrors chain_add.build_block; verified byte-identical).
# each op over each tile -> one 16-qword block. the 3 DMA-address slots (qword 12=dst, 13=src, 14=ew) are left 0 and patched
# by the runtime once the buffers exist, so the runtime only allocates + patches addresses + submits -- it generates no command.
_DPU, _RDMA = 0x1001, 0x2001
def _E(t, reg, v): return (t << 48) | ((v & 0xFFFFFFFF) << 16) | reg
_EW_OPS = {"ADD":(0x108002c0|(2<<16),(1<<16)|1,1), "MUL":(0x108002c0|(1<<2)|(1<<8),(1<<16)|1,1),    # (EW_CFG, OUT_CVT_SCALE, fp16->fp32)
           "SUB":(0x108002c0|(4<<16),(1<<16)|1,1), "DIV":(0x108002c0|(3<<16)|(1<<8),1,0)}
EW_TILE = 8000*8   # one DPU task covers <=64000 elems (DATA_CUBE_WIDTH limit); a larger n is split into back-to-back tile tasks
def _ew_block(op, tile_n):
  cfg, cvt, f32 = _EW_OPS[op]; dw = (tile_n + 7)//8 - 1; rf = (2<<15)|(15<<11)|(2<<5)|(f32<<3)|1
  return [_E(_DPU,0x4004,0xe), _E(_RDMA,0x5004,0xe), 0x1001000001e5400c, 0x1001480000024010, 0x100100070007403c,
          _E(_DPU,0x4030,dw), _E(_DPU,0x4070,cfg), _E(_DPU,0x4084,cvt), _E(_RDMA,0x500c,dw),
          0x2001000000005010, 0x2001000700075014, 0x2001400000085034,
          _E(_DPU,0x4020,0), _E(_RDMA,0x5018,0), _E(_RDMA,0x5038,0), _E(_RDMA,0x5044,rf)]   # [12]=dst [13]=src [14]=ew (patched at run)
def ew_command(d):
  # the full NPU job for an EW descriptor: tiling + per-(task,tile) command blocks, each tagged with its src/ew/dst buffer ref.
  # chain_add lays out per-(operand,tile) buffers; task k tile t reads its operands' tile-t buffers and writes result-k tile t.
  n = d["n"]; tiles = [(s, min(EW_TILE, n-s)) for s in range(0, n, EW_TILE)]
  blocks = [(_ew_block(op, tn), sa, sb, ("node", k), t) for k,(op,sa,sb) in enumerate(d["tasks"]) for t,(_s,tn) in enumerate(tiles)]
  return {"tiles": tiles, "blocks": blocks, "nleaf": len(d["leaves"]), "ntask": len(d["tasks"]), "out_task": len(d["tasks"])-1}

# --- the NPU MAC (GEMM) register command. the vendor make_gemm_regs (gemm.py) is ~45 intricate qwords; rather than re-typing
# it (reboot-risky), the renderer CALLS it at compile time (it's pure -- no NPU/ioctl) with addr=0, tiling M like run_gemm, and
# stores the resulting command. the 3 DMA-address slots (input=0x1070, weight=0x1110, output=0x4020) are patched by the runtime.
_GEMM_ADDR = (0x1070, 0x1110, 0x4020)
def _patch_gemm(qwords, in_a, wt_a, out_a):
  amap = {0x1070:in_a, 0x1110:wt_a, 0x4020:out_a}
  return [(q & ~(0xFFFFFFFF<<16)) | ((amap[q&0xFFFF]&0xFFFFFFFF)<<16) if (q&0xFFFF) in amap else q for q in qwords]
def gemm_command(g):
  # render the GEMM command for one extracted MAC: per M-tile, _make_gemm_regs(tile_m,N,k_eff) with addr=0 + the tile's input/
  # output byte offsets. vector bias -> augmented matmul (k_eff=K+1, no bias in regs); scalar bias -> DPU BS in regs. (the
  # WEIGHT/INPUT data packing stays in the runtime -- it's data, not command.)
  M, K, N, bias = g[0], g[1], g[2], g[15]
  augment = isinstance(bias, tuple); k_eff = K+1 if augment else K
  ai, ao, _ = _gemm_layout(M, N, k_eff); in_row, out_row = ai*2, ao*4
  m_tile = 10*32768 // in_row if ai <= 384 else 1            # GEMM_INPUT_BANKS(10) * CBUF_BANK_SIZE(32768) / input_row_bytes
  tiles = [(s*in_row, s*out_row, _make_gemm_regs(min(m_tile, M-s), N, k_eff, 0, 0, 0, bias=None if augment else bias))
           for s in range(0, M, m_tile)]
  return {"tiles": tiles, "k_eff": k_eff, "augment": augment, "align_in": ai, "align_out": ao}

def extract_elementwise(sink:UOp):
  # the ALU analogue of extract_matmul: detect a pure elementwise kernel (NO reduce) whose single STORE value is a
  # DAG of EW binops over affine LOADs/consts, and return it as a STRUCTURED task graph over the loop RANGE(s) --
  # rendered as one structured clang loop (ew_lines), WITHOUT unrolling. None if it isn't a representable contiguous EW graph.
  topo = list(sink.toposort())
  if any(u.op is Ops.RANGE and u.arg[1] is AxisType.REDUCE for u in topo): return None   # has a reduce -> not pure EW
  stores = [u for u in topo if u.op is Ops.STORE]
  if len(stores) != 1 or stores[0].src[0].op is not Ops.INDEX or stores[0].src[0].src[0].op is not Ops.PARAM: return None
  if stores[0].src[1].dtype.scalar() not in NPF: return None               # the NPU EW / clang ew_lines are fp16/fp32 only -> other dtypes stay a C loop
  rngs = [u for u in topo if u.op is Ops.RANGE]
  if not rngs: return None
  n = 1
  for r in rngs: n *= r.vmax+1
  # row-major flatten strides; a leaf is only tile-expressible if its affine index map matches them (contiguous).
  strides, acc = [], 1
  for r in reversed(rngs): strides.insert(0, acc); acc *= r.vmax+1
  iv = lambda e, vm: graph_rewrite(e.substitute({r: r.const_like(v) for r, v in vm.items()}), symbolic).arg
  def affine(idx):
    base = iv(idx, {r:0 for r in rngs})
    return base, [iv(idx, {**{rr:0 for rr in rngs}, r:1})-base for r in rngs]
  def leaf(u):
    # ('const', value) or ('buf', bufid, base) for a contiguous affine load; else None (not a tile leaf)
    if u.op is Ops.CONST: return ("const", u.arg)
    if u.op is Ops.LOAD and u.src[0].op is Ops.INDEX and u.src[0].src[0].op is Ops.PARAM:
      base, coeffs = affine(u.src[0].src[1])
      return ("buf", u.src[0].src[0].arg, base) if coeffs == strides else None
    return None
  # walk the store value into a task DAG: each EW binop -> one task (op, src_ref, ew_ref). a ref is
  # ("leaf", i) for an input operand (contiguous load or broadcast const) or ("node", k) for task k's result.
  # shared subexpressions collapse to a single task, so the whole ALU graph is one structured loop.
  leaves, leaf_idx, tasks, node_of = [], {}, [], {}
  def leaf_ref(lf):
    if lf not in leaf_idx: leaf_idx[lf] = len(leaves); leaves.append(lf)
    return ("leaf", leaf_idx[lf])
  def build(v):
    if (lf:=leaf(v)) is not None: return leaf_ref(lf)
    if v in node_of: return ("node", node_of[v])                                       # reuse a shared subexpr
    if v.op not in EW_BINOPS or len(v.src) != 2: return None                            # not an EW op -> not extractable
    if (ra:=build(v.src[0])) is None or (rb:=build(v.src[1])) is None: return None
    node_of[v] = len(tasks); tasks.append((EW_BINOPS[v.op], ra, rb))                    # children first -> topo order
    return ("node", node_of[v])
  obase, ocoeffs = affine(stores[0].src[0].src[1])
  # the whole store is one chain_add submit (PC-chained DPU-EW tasks); cap the op count (EW_MAX_OPS), else fall to a C loop
  if ocoeffs != strides or (root:=build(stores[0].src[1])) is None or root[0] != "node" or len(tasks) > EW_MAX_OPS: return None
  return {"n": n, "out": (stores[0].src[0].src[0].arg, obase), "tasks": tasks, "leaves": leaves, "dt": NPF[stores[0].src[1].dtype.scalar()]}

def peel_ew_subdags(uops:list[UOp]):
  # a MIXED elementwise compact loop whose store value has an op the NPU DPU-EW can't do (compare/cast/max/mod/...):
  # find each MAXIMAL float EW-binop sub-DAG (contiguous-affine leaves) and group it onto the NPU (chain_add) into a
  # SCRATCH buffer. returns (ews, scratch): `ews` are NPU EW descriptors (out = a scratch id PAST the real params) and
  # `scratch` maps each sub-DAG ROOT uop -> its scratch id, so compact_loop_to_c renders the root as a scratch LOAD and
  # the non-EW remainder as a CPU loop. NO buffer is added to the kernel's globals -- the scratch lives only in render +
  # the runtime (which allocates it). so e.g. (a+b)>c becomes ONE NPU add + a CPU compare.
  stores = [u for u in uops if u.op is Ops.STORE]
  rngs = [u for u in uops if u.op is Ops.RANGE]
  if len(stores) != 1 or not rngs: return [], {}
  n = 1
  for r in rngs: n *= r.vmax+1
  strides, acc = [], 1
  for r in reversed(rngs): strides.insert(0, acc); acc *= r.vmax+1                       # row-major flatten strides
  iv = lambda e, vm: graph_rewrite(e.substitute({r: r.const_like(v) for r, v in vm.items()}), symbolic).arg
  def affine(idx):
    base = iv(idx, {r:0 for r in rngs})
    return base, [iv(idx, {**{rr:0 for rr in rngs}, r:1})-base for r in rngs]
  def leaf(u):
    if u.op is Ops.CONST: return ("const", u.arg)
    if u.op is Ops.LOAD and u.src[0].op is Ops.INDEX and u.src[0].src[0].op is Ops.PARAM:
      base, coeffs = affine(u.src[0].src[1])
      return ("buf", u.src[0].src[0].arg, base) if coeffs == strides else None
    return None
  memo:dict = {}
  def extractable(u):   # u's whole subtree is a float EW-binop DAG over contiguous leaves -> runnable as one NPU EW
    if u not in memo: memo[u] = (leaf(u) is not None) or (u.op in EW_BINOPS and len(u.src) == 2 and
                                                          u.dtype.scalar() in NPF and all(extractable(s) for s in u.src))
    return memo[u]
  if extractable(stores[0].src[1]): return [], {}           # whole store is EW -> extract_elementwise handled it upstream
  cons:dict = {}                                            # maximal roots = an extractable EW-binop feeding a NON-extractable
  for u in uops:                                            # consumer (these are disjoint; a bare leaf isn't worth a submit)
    for s in u.src: cons.setdefault(s, []).append(u)
  roots = [u for u in uops if u.op in EW_BINOPS and extractable(u) and any(not extractable(c) for c in cons.get(u, []))]
  if not roots: return [], {}
  def taskgraph(root):                                       # the chain_add task DAG for one sub-DAG (children-first, shared collapse)
    leaves, leaf_idx, tasks, node_of = [], {}, [], {}
    def ref(v):
      if (lf:=leaf(v)) is not None:
        if lf not in leaf_idx: leaf_idx[lf] = len(leaves); leaves.append(lf)
        return ("leaf", leaf_idx[lf])
      if v in node_of: return ("node", node_of[v])
      ra, rb = ref(v.src[0]), ref(v.src[1])
      node_of[v] = len(tasks); tasks.append((EW_BINOPS[v.op], ra, rb))
      return ("node", node_of[v])
    ref(root); return tasks, leaves
  nreal = max(u.arg for u in uops if u.op is Ops.PARAM) + 1  # scratch buffer ids start past the real kernel buffers
  ews, scratch = [], {}
  for root in roots:
    tasks, leaves = taskgraph(root)
    if len(tasks) > EW_MAX_OPS: continue                     # too long to PC-chain in one submit -> leave this sub-DAG on the CPU
    sid = nreal + len(scratch)
    ews.append({"n": n, "out": (sid, 0), "tasks": tasks, "leaves": leaves, "dt": NPF[root.dtype.scalar()]}); scratch[root] = sid
  return ews, scratch

def extract_bias_vector(sink:UOp):
  # after extract_matmul, detect a pure  C[m,n] + bias[n]  epilogue (per-column bias, broadcast over rows): the store
  # value is ADD(LOAD C[m,n] in place, LOAD bias[<contiguous axis only>]). record it as a bias VECTOR for the GEMM
  # (run_gemm augments [x|1]@[W;b]) and drop the store. None if it isn't exactly that shape.
  topo = list(sink.toposort())
  stores = [u for u in topo if u.op is Ops.STORE]
  if len(stores) != 1: return None
  st = stores[0]; cidx = st.src[0]
  if cidx.op is not Ops.INDEX or cidx.src[0].op is not Ops.PARAM or st.src[1].op is not Ops.ADD or len(st.src[1].src) != 2: return None
  selfl = [s for s in st.src[1].src if s.op is Ops.LOAD and s.src[0] is cidx]                       # in-place GEMM output read
  biasl = [s for s in st.src[1].src if s.op is Ops.LOAD and s.src[0].op is Ops.INDEX and s.src[0] is not cidx and
           s.src[0].src[0].op is Ops.PARAM]
  if len(selfl) != 1 or len(biasl) != 1: return None
  bidx = biasl[0].src[0].src[1]                                                                     # bias index expression
  orng = {u for u in cidx.src[1].toposort() if u.op is Ops.RANGE}                                   # the (M,N) output ranges
  brng = {u for u in bidx.toposort() if u.op is Ops.RANGE}
  if len(brng) != 1 or not brng <= orng: return None                                                # bias indexes exactly one axis
  ncol = next(iter(brng))
  iv = lambda e, vm: graph_rewrite(e.substitute({r: r.const_like(v) for r, v in vm.items()}), symbolic).arg
  z = {r: 0 for r in orng}
  if iv(cidx.src[1], {**z, ncol: 1}) - iv(cidx.src[1], z) != 1: return None                          # must be the contiguous (column) axis
  base, stride = iv(bidx, z), iv(bidx, {**z, ncol: 1}) - iv(bidx, z)
  _RK_BIAS.append((cidx.src[0].arg, biasl[0].src[0].src[0].arg, base, stride, ncol.vmax + 1))
  return UOp.sink(*[UOp(Ops.NOOP, dtypes.void, (p,)) for p in dedup([u for u in topo if u.op is Ops.PARAM])], arg=sink.arg)

def rk_sink(sink:UOp):
  s, mm = sink, extract_matmul(sink)                       # pull the GEMM out first (structured M,K,N), then...
  if mm is not None: s = mm
  bv = extract_bias_vector(s) if mm is not None else None  # ...a  C[m,n]+bias[n]  epilogue -> a per-column bias VECTOR on the GEMM
  if bv is not None: s = bv
  ew = extract_elementwise(s) if bv is None else None      # ...else pull the (whole-store) elementwise epilogue out structurally too
  if ew is not None:
    _RK_EW.append(ew)
    # the epilogue is now a descriptor; drop its store/ranges but keep every param reachable so globals stays correct
    s = UOp.sink(*[UOp(Ops.NOOP, dtypes.void, (p,)) for p in dedup([u for u in s.toposort() if u.op is Ops.PARAM])], arg=s.arg)
  if mm is None and ew is None: return None                # nothing structured -> leave the sink compact; render emits a C loop
  # (a MIXED EW store -- one with a non-EW op like a compare -- is left compact here; render's peel_ew_subdags then groups
  # its float-ALU sub-DAGs onto the NPU and renders the rest as a C loop, without adding a buffer to the kernel's globals.)
  return s                                                 # something extracted; re-apply, then render the leftover as a C loop
rk_prepare = PatternMatcher([(UPat(Ops.SINK, name="sink"), rk_sink)])+symbolic

class RKRenderer(Renderer):
  has_local = False
  supports_float4 = False                   # scalar stream: compact_loop_to_c renders scalar loads/stores, not vec4
  structured_reduce = True                   # keep matmul as raw M,K,N ranges so extract_matmul can pull it out
  full_unroll_reduces = False               # keep non-matmul reductions as register-accumulator loops -> compact_loop_to_c
  # native ops must be a subset of what the uop runtime (python_alu) can execute; keep transcendentals native
  # so they don't decompose into float<->int bitcast (which ONNX can't express). (no FDIV -> uses RECIPROCAL+MUL)
  code_for_op = {Ops.ADD:"+", Ops.SUB:"-", Ops.MUL:"*", Ops.CMPLT:"<", Ops.CMPNE:"!=", Ops.MAX:"max",
                 Ops.SIN:"sin", Ops.SQRT:"sqrt", Ops.EXP2:"exp2", Ops.LOG2:"log2", Ops.RECIPROCAL:"recip"}
  pre_matcher = rk_prepare
  def render(self, uops:list[UOp]) -> str:
    idx = {u:i for i,u in enumerate(uops)}
    if not any(u.op is Ops.RANGE for u in uops):   # fully extracted: no leftover compute -- only structured GEMMs + EWs.
      # GEMMs (extract_matmul) write straight to C; the EW (extract_elementwise / extract_bias_vector) is a descriptor.
      gemms = list(_RK_GEMM); _RK_GEMM.clear(); ews = list(_RK_EW); _RK_EW.clear()
      # the GEMM runs on the NPU MAC (vendor gemm.py). an epilogue that is exactly  C + const  FUSES into the GEMM's DPU
      # bias unit (run_gemm bias=); a  C + bias[n]  -> a per-column bias VECTOR (augmentation). detect & drop those EWs;
      # any other EW runs on the NPU DPU-EW (chain_add), with a clang fallback (ew_lines, fp32) if the submit fails.
      bias:dict = {}
      for ew in (ews if gemms else []):
        t, lv = ew["tasks"], ew["leaves"]
        if len(t) == 1 and t[0][0] == "ADD":
          bl = [lv[r[1]] for r in t[0][1:3] if r[0] == "leaf" and lv[r[1]][0] == "buf"]      # buffer operand(s)
          cl = [lv[r[1]][1] for r in t[0][1:3] if r[0] == "leaf" and lv[r[1]][0] == "const"] # const operand(s)
          # one operand is the GEMM output C (read & written back in place), the other a broadcast const
          if len(bl) == 1 and len(cl) == 1 and ew["out"] == (bl[0][1], bl[0][2]) and any(bl[0][1] == g[11] for g in gemms):
            bias[bl[0][1]] = cl[0]
      ews = [ew for ew in ews if ew["out"][0] not in bias]                                    # fused const epilogues removed
      vbias = {ob: (bp, base, stride, nn) for (ob, bp, base, stride, nn) in _RK_BIAS}; _RK_BIAS.clear()
      # per-GEMM bias carried to the runtime: a float (-> DPU BS ALU) or a (param,base,stride,N) spec (-> augmentation) or None
      npu_gemm = [g + (bias.get(g[11], vbias.get(g[11])),) for g in gemms]
      # the leftover EW(s) run on the NPU DPU-EW FIRST -- the renderer attaches the register command (ew_command); the runtime
      # just submits it -- with a structured clang loop (ew_lines) as the CPU fallback if the submit fails (e.g. §8.3 ENXIOs it).
      for e in ews: e["npu"] = ew_command(e)
      npu_gemm_cmd = [gemm_command(g) for g in npu_gemm]       # the renderer also generates each GEMM's NPU register command
      prog:list = [("ew", e) for e in ews]
      if DEBUG >= 6:
        for g in gemms: print(f"  GEMM (M={g[0]} K={g[1]} N={g[2]} -> C[{g[11]}]" +
                              (f" + {bias[g[11]]} fused (DPU BS)" if g[11] in bias else
                               f" + bias[{g[2]}] fused (augment buf{vbias[g[11]][0]})" if g[11] in vbias else "") + ") on NPU MAC")
      return base64.b64encode(pickle.dumps(("chunks", prog, npu_gemm, npu_gemm_cmd))).decode()
    if DEBUG >= 6:
      print(f"RKRenderer: {len(uops)} compact uops:")
      for u in uops:
        print(f"  %{idx[u]:<3d} = {u.op.name:12s} {u.dtype}" + (" src=("+", ".join(f'%{idx[s]}' for s in u.src)+")" if u.src else "") +
              ("" if u.arg is None else f" arg={u.arg}"))
    ews_sub, scratch = peel_ew_subdags(uops)   # group a MIXED kernel's float-ALU sub-DAGs (e.g. the a+b in (a+b)>c) onto the NPU
    cl = compact_loop_to_c(uops, scratch)       # render the leftover compact loop straight to clang C; raises if an op/dtype
    # can't render (no uop interpreter -- every op the RK renderer emits is renderable). a GEMM extracted before it (matmul +
    # a non-extractable epilogue, e.g. (a@b).relu()) still runs on the NPU first; a peeled float-ALU sub-DAG (ews_sub) runs on
    # the NPU into a scratch buffer the cloop reads; the non-EW remainder (compare/cast/max/...) stays in the C loop.
    gemms = list(_RK_GEMM); _RK_GEMM.clear(); ews = list(_RK_EW); _RK_EW.clear(); _RK_BIAS.clear()
    npu_gemm = [g+(None,) for g in gemms]
    npu_gemm_cmd = [gemm_command(g) for g in npu_gemm]         # the renderer attaches each GEMM's NPU register command...
    for e in ews + ews_sub: e["npu"] = ew_command(e)           # ...and each EW's
    prog:list = [("ew", e) for e in ews + ews_sub] + [("cloop", cl[0], cl[1])]
    if DEBUG >= 3: print(f"RKRenderer: {len(uops)} compact uops -> clang C loop (CPU)" +
                         (f", after {len(gemms)} NPU GEMM" if gemms else "") +
                         (f" + {len(ews_sub)} NPU EW sub-DAG" if ews_sub else "") + ":\n" + "\n".join(cl[0]))
    return base64.b64encode(pickle.dumps(("chunks", prog, npu_gemm, npu_gemm_cmd))).decode()

class RKCompiler(Compiler):
  def compile(self, src:str) -> bytes: return base64.b64decode(src)
RKRenderer.compiler = RKCompiler()

CT = {dtypes.float:"float", dtypes.half:"_Float16", dtypes.double:"double", dtypes.bool:"unsigned char", dtypes.int:"int",
      dtypes.uint:"unsigned int", dtypes.long:"long long", dtypes.ulong:"unsigned long long"}
C_BIN = {Ops.ADD:"+", Ops.SUB:"-", Ops.MUL:"*", Ops.FDIV:"/", Ops.CDIV:"/", Ops.CMOD:"%", Ops.CMPLT:"<",
         Ops.CMPNE:"!=", Ops.CMPEQ:"==", Ops.AND:"&", Ops.OR:"|", Ops.XOR:"^", Ops.SHL:"<<", Ops.SHR:">>"}
C_FN = {Ops.SQRT:"sqrt", Ops.SIN:"sin", Ops.EXP2:"exp2", Ops.LOG2:"log2"}   # __builtin_<fn>[f]

def chunks_to_c(gemms, prog) -> tuple[list[str], list[str], int]:
  # render the clang CPU fallbacks: one `void gN(void** B)` per NPU GEMM (mm_lines) and one `void kN(void** B)` per EW/cloop
  # submit (ew_lines / the compact loop body). a g/k fxn runs only if its NPU path fails; each writes straight to its output(s).
  is_ew = lambda sub: isinstance(sub, tuple) and sub[0] == "ew"
  is_cloop = lambda sub: isinstance(sub, tuple) and sub[0] == "cloop"     # ("cloop", body_lines, nbufs): a compact loop
  EW_C = {"ADD":"+", "MUL":"*", "SUB":"-", "DIV":"/"}
  def mm_lines(M, K, N, bufA, bufB, ba, am, ak, bb, bk, bn, bufC, cb, cm, cn, bias):
    # fp32 matmul  C[m,n] = sum_k A[m,k]*B[k,n] (+bias)  -- the same affine A/B/C index maps the NPU GEMM uses.
    bt = "" if bias is None else f"+((float*)b[{bias[0]}])[{bias[1]}+{bias[2]}*n]" if isinstance(bias, tuple) else f"+{float(bias)}f"
    return [f"for(int m=0;m<{M};m++)for(int n=0;n<{N};n++){{", "  float acc=0;",
            f"  for(int k=0;k<{K};k++)acc+=((float*)b[{bufA}])[{ba}+{am}*m+{ak}*k]*((float*)b[{bufB}])[{bb}+{bk}*k+{bn}*n];",
            f"  ((float*)b[{bufC}])[{cb}+{cm}*m+{cn}*n]=acc{bt};", "}"]
  def ew_lines(d):
    # the structured elementwise graph (extract_elementwise) as one C loop over n: each task is a binop over leaf
    # buffers/consts or a prior task, writing the root straight to the output. no unroll -- the loop IS the range. the
    # buffer reads/write use the kernel's float C type ({float|_Float16}) so the fp16 fallback matches the buffer width.
    leaves, tasks, (ob, obase) = d["leaves"], d["tasks"], d["out"]
    cty = {"float32":"float", "float16":"_Float16"}[d["dt"]]
    refc = lambda r: (f"(({cty}*)b[{leaves[r[1]][1]}])[{leaves[r[1]][2]}+i]" if leaves[r[1]][0] == "buf" else f"{float(leaves[r[1]][1])}f") \
                     if r[0] == "leaf" else f"t{r[1]}"
    body = [f"for(int i=0;i<{d['n']};i++){{"]
    for k, (op, ra, rb) in enumerate(tasks):
      body.append(f"  float t{k} = " + (f"fmaxf({refc(ra)},{refc(rb)})" if op == "MAX" else f"({refc(ra)}{EW_C[op]}{refc(rb)})") + ";")
    return body + [f"  (({cty}*)b[{ob}])[{obase}+i] = t{len(tasks)-1};", "}"]
  gemm_bufs = [b for g in gemms for b in (g[3], g[4], g[11])] + [g[15][0] for g in gemms if isinstance(g[15], tuple)]  # A,B,C (+bias buf)
  ew_bufs = [b for sub in prog if is_ew(sub) for b in [sub[1]["out"][0]] + [lf[1] for lf in sub[1]["leaves"] if lf[0] == "buf"]]
  nbufs = max([1] + [b+1 for b in gemm_bufs + ew_bufs] + [sub[2] for sub in prog if is_cloop(sub)])
  wrap = lambda nm, lines: f"void {nm}(void** B){{ char** b=(char**)B;\n" + "\n".join(lines) + "\n}\n"
  gsubs = [wrap(f"g{gi}", mm_lines(*g)) for gi, g in enumerate(gemms)]
  submits = [wrap(f"k{si}", ew_lines(sub[1]) if is_ew(sub) else sub[1] if is_cloop(sub) else []) for si, sub in enumerate(prog)]
  return gsubs, submits, nbufs

def compact_loop_to_c(uops:list[UOp], scratch:dict|None=None):
  # render a COMPACT looped sink -- elementwise AND reductions (via the register-accumulator form: DEFINE_REG + a
  # zero-store, an in-reduce-loop update store, then an output store) -- straight to one C function with nested
  # for-loops, by walking the uops in linearized order (RANGE->`for{`, END->`}`, STORE->assignment). directly from the
  # uops: NO unroll, NO per-element scalars. returns ([submit], nbufs); raises NotImplementedError if an op/dtype can't render.
  # `scratch` (from peel_ew_subdags) maps a sub-DAG ROOT uop -> a scratch buffer id: that root renders as a read of the
  # row-major scratch (the NPU already computed it) instead of recursing into its (now offloaded) float-ALU subtree.
  if not any(u.op is Ops.RANGE for u in uops): return None
  scratch = scratch or {}
  bufs = {u: u.arg for u in uops if u.op is Ops.PARAM}
  regs = {u: f"acc{i}" for i, u in enumerate(u for u in uops if u.op is Ops.DEFINE_REG)}
  rng:dict = {}
  rs = [u for u in uops if u.op is Ops.RANGE]                   # row-major scratch flatten: outermost range has the largest stride
  sst, a = {}, 1
  for r in reversed(rs): sst[r] = a; a *= r.vmax+1
  def sflat(): return "+".join(rng[r] if sst[r] == 1 else f"{rng[r]}*{sst[r]}" for r in rs) or "0"
  def ct2(dt):
    if (s:=dt.scalar()) not in CT: raise NotImplementedError(s)
    return CT[s]
  def memref(ix):                                               # INDEX uop -> ("reg",name) or ("buf",bufid,index_uop)
    p = ix.src[0]
    while p.op in (Ops.CAST, Ops.AFTER): p = p.src[0]           # AFTER/CAST are dependency/ptr wrappers -> the base
    if p.op is Ops.DEFINE_REG: return ("reg", regs[p])
    if p.op is Ops.PARAM: return ("buf", bufs[p], ix.src[1])
    raise NotImplementedError(f"index base {p.op}")
  def ce(u):                                                    # render a value / index uop to a C expression
    if u in scratch: return f"(({ct2(u.dtype)}*)b[{scratch[u]}])[{sflat()}]"   # NPU already computed this sub-DAG -> read scratch
    if u.op is Ops.CONST:
      if u.dtype is dtypes.bool: return "1" if u.arg else "0"
      if not dtypes.is_float(u.dtype): return str(int(u.arg))
      v = float(u.arg)                                          # 'inff'/'nanf' aren't valid C literals -> use the builtins
      if math.isinf(v): return ("-" if v < 0 else "") + "__builtin_inff()"
      if math.isnan(v): return "__builtin_nanf(\"\")"
      return f"{v!r}f" if u.dtype.scalar() in (dtypes.float, dtypes.half) else repr(v)
    if u.op is Ops.RANGE: return rng[u]
    if u.op is Ops.CAST: return f"({ct2(u.dtype)})({ce(u.src[0])})"
    if u.op is Ops.LOAD:
      mr = memref(u.src[0]); return mr[1] if mr[0] == "reg" else f"(({ct2(u.dtype)}*)b[{mr[1]}])[{ce(mr[2])}]"
    es, op, f, c = [ce(s) for s in u.src], u.op, ('f' if u.dtype.scalar() in (dtypes.float, dtypes.half) else ''), ct2(u.dtype)
    if op is Ops.MAX: return f"(({es[0]})>({es[1]})?({es[0]}):({es[1]}))"
    if op is Ops.WHERE: return f"(({es[0]})?({es[1]}):({es[2]}))"
    if op is Ops.TRUNC: return f"__builtin_trunc{f}({es[0]})" if f else f"({es[0]})"   # int trunc is a no-op; float/round family decompose to this
    if op is Ops.NEG: return f"(-({es[0]}))"
    if op is Ops.RECIPROCAL: return f"((({c})1)/({es[0]}))"
    if op is Ops.MULACC: return f"(({es[0]})*({es[1]})+({es[2]}))"
    if op is Ops.BITCAST: return f"({{ {ct2(u.src[0].dtype)} _s=({es[0]}); {c} _d; __builtin_memcpy(&_d,&_s,sizeof(_d)); _d; }})"
    if op is Ops.FLOORDIV: return f"__builtin_floor{f}(({es[0]})/({es[1]}))" if f else \
                                  f"({{ {c} _a=({es[0]}),_b=({es[1]}),_m=((_a%_b)+_b)%_b; (_a-_m)/_b; }})"
    if op is Ops.FLOORMOD: return f"({{ {c} _a=({es[0]}),_b=({es[1]}); _a-_b*__builtin_floor{f}(_a/_b); }})" if f else \
                                  f"({{ {c} _a=({es[0]}),_b=({es[1]}); ((_a%_b)+_b)%_b; }})"
    if op in C_FN: return f"__builtin_{C_FN[op]}{f}({es[0]})"
    if op in C_BIN: return f"(({es[0]}){C_BIN[op]}({es[1]}))"
    raise NotImplementedError(f"RK cloop: op {op}")
  regdt:dict = {}
  lines, depth = [], 1
  for u in uops:                                                # walk in linearized order: ranges open/close loops
    if u.op is Ops.RANGE:
      rng[u] = f"r{len(rng)}"; lines.append("  "*depth + f"for(int {rng[u]}=0;{rng[u]}<{u.vmax+1};{rng[u]}++){{"); depth += 1
    elif u.op is Ops.END: depth -= 1; lines.append("  "*depth + "}")
    elif u.op is Ops.STORE:                                     # ce()/ct2() raise NotImplementedError(op/dtype) if it can't render to C
      mr = memref(u.src[0])
      if mr[0] == "reg":
        p = u.src[0].src[0]
        while p.op in (Ops.CAST, Ops.AFTER): p = p.src[0]
        regdt[p] = u.src[1].dtype; dest = mr[1]
      else: dest = f"(({ct2(u.src[1].dtype)}*)b[{mr[1]}])[{ce(mr[2])}]"
      lines.append("  "*depth + f"{dest} = {ce(u.src[1])};")
  return [f"{ct2(regdt.get(r, dtypes.float))} {n};" for r, n in regs.items()] + lines, \
         max(list(bufs.values()) + list(scratch.values())) + 1   # (decls + loop body), nbufs (incl. any scratch ids)

def _run_npu_ew(d, bufs, st):
  # RUN the renderer-generated DPU-EW command (d["npu"]): on first call allocate the per-(operand,tile) NPU buffers and patch
  # each block's 3 DMA-address slots; then lay the regcmd, write the input as fp16, submit. numpy-free: an fp16 source buffer's
  # bytes pass straight through (memmove); an fp32 source is narrowed with struct; the result mirrors that back to the output.
  npu = _npu(); P = d["npu"]; tiles = P["tiles"]; n = d["n"]; isz = 2 if d["dt"] == "float16" else 4
  if "task_regs" not in st:                                   # allocate resident buffers + patch addresses once (then reuse)
    tb = lambda tn: max(4096, (tn*2+255)//256*256)
    st["leaf"] = [[npu.alloc(tb(tn), 0) for (_s,tn) in tiles] for _ in range(P["nleaf"])]
    st["res"]  = [[npu.alloc(tb(tn), 0) for (_s,tn) in tiles] for _ in range(P["ntask"])]
    addr = lambda ref,t: ((st["leaf"] if ref[0] == "leaf" else st["res"])[ref[1]][t])[1].dma_addr
    st["task_regs"] = []
    for qw, sa, sb, dr, t in P["blocks"]:
      q = list(qw); q[12] = _E(_DPU,0x4020,addr(dr,t)); q[13] = _E(_RDMA,0x5018,addr(sa,t)); q[14] = _E(_RDMA,0x5038,addr(sb,t))
      st["task_regs"].append(q)
  npu.write_regs(st["task_regs"], 0x18, True, 0)              # DPU-EW: OPERATION_ENABLE=0x18, op_idx=task idx, end-NOP=0
  for i, lf in enumerate(d["leaves"]):                        # the fp16 bytes for this operand, scattered into the per-tile buffers
    f16 = _f16([float(lf[1])]*n) if lf[0] == "const" else bytes(bufs[lf[1]][lf[2]*2:(lf[2]+n)*2]) if isz == 2 else \
          _f16(list(struct.unpack(f"<{n}f", bufs[lf[1]][lf[2]*4:(lf[2]+n)*4])))
    for t,(s,tn) in enumerate(tiles): st["leaf"][i][t][0][:tn*2] = f16[s*2:(s+tn)*2]
  npu.submit(len(st["task_regs"]))
  ob, obase = d["out"]; out = bytearray(n*2)                  # gather the last task's tiles (fp16) back together
  for t,(s,tn) in enumerate(tiles): out[s*2:(s+tn)*2] = st["res"][P["out_task"]][t][0][:tn*2]
  if isz == 2: bufs[ob][obase*2:(obase+n)*2] = bytes(out)     # fp16 output -> the fp16 bytes straight through
  else: bufs[ob][obase*4:(obase+n)*4] = struct.pack(f"<{n}f", *struct.unpack(f"<{n}e", bytes(out)))

def _run_npu_gemm(g, plan, bufs):
  # RUN the renderer-generated GEMM command (plan): pack the fp16 input + 16x32-tiled weight into the NPU's resident buffers,
  # patch each M-tile command's 3 DMA-address slots, submit, de-interleave the fp32 output. numpy-free -- the layout transforms
  # (pad / 16x32 tile / de-interleave) are plain index gathers, the fp16 narrowing is struct. equivalent to the old run_gemm.
  M,K,N,bufA,bufB,ba,am,ak,bb,bk,bn,bufC,cb,cm,cn,bias = g
  npu = _npu(); (imap,imc),(wmap,wmc),(omap,omc) = npu.gemm_bufs()
  ai, ao, ke = plan["align_in"], plan["align_out"], plan["k_eff"]
  A = list(struct.unpack(f"<{M*K}f", bufs[bufA][ba*4:(ba+M*K)*4]))   # row-major M*K (GEMM is fp32-gated -> fp32 buffers)
  B = list(struct.unpack(f"<{K*N}f", bufs[bufB][bb*4:(bb+K*N)*4]))   # row-major K*N
  if plan["augment"]:                                          # x@W + b[n]  ->  [x|1] @ [W;b]  (k_eff=K+1: A gains a 1-col, B a bias-row)
    bp, base, stride, NN = bias; sN = stride or 1
    bv = list(struct.unpack(f"<{sN*NN}f", bufs[bp][base*4:(base+sN*NN)*4]))[::sN][:NN]
    A = [A[m*K+c] if c < K else 1.0 for m in range(M) for c in range(K+1)]; B = B + bv
  inp = [A[m*ke+c] if c < ke else 0.0 for m in range(M) for c in range(ai)]               # input, padded to align_in wide
  wp = [0.0]*(ao*ai); rt = ai//32                                                          # weight, B.T padded then 16x32-tiled
  for b0 in range(ao//16):
    for b1 in range(rt):
      for r in range(16):
        row = b0*16+r
        for c in range(32):
          col = b1*32+c
          if row < N and col < ke: wp[((b0*rt+b1)*16+r)*32+c] = B[col*N+row]
  imap[:len(inp)*2] = _f16(inp); wmap[:len(wp)*2] = _f16(wp)
  task_regs = [_patch_gemm(t[2], imc.dma_addr+t[0], wmc.dma_addr, omc.dma_addr+t[1]) for t in plan["tiles"]]
  npu.write_regs(task_regs, 0xd, False, _E(0x0001,0,0))      # MAC: OPERATION_ENABLE=0xd, op_idx=0, end-NOP=E(0x0001,0,0)
  if npu.submit(len(task_regs), reset=True) < 0: raise RuntimeError("npu_submit failed")
  out = struct.unpack(f"<{M*ao}f", omap[:M*ao*4])             # fp32 padded output; de-interleave row m at stride align_out
  bufs[bufC][cb*4:(cb+M*N)*4] = struct.pack(f"<{M*N}f", *(out[m*ao+n] for m in range(M) for n in range(N)))

class RKProgram:
  def __init__(self, device:str, name:str, lib:bytes, *args, **kwargs):
    self.device, self.name, self.prog = device, name, pickle.loads(lib)
    self._fxns:list = []; self._gemm_fxns:list = []; self._ew_cache:dict = {}   # resident NPU buffers per EW submit
    self._npu_gemm = self.prog[2] if self.prog[0] == "chunks" else None    # GEMMs to run on the NPU MAC, or None
    self._npu_gemm_cmd = self.prog[3] if self.prog[0] == "chunks" else None # the renderer-generated GEMM register command per GEMM
    if self.prog[0] == "chunks":                                # clang CPU fallbacks: one per NPU GEMM + one per EW/cloop submit
      gsubs, submits, self._nbufs = chunks_to_c(self._npu_gemm, self.prog[1])
      if DEBUG >= 6:
        for si, src in enumerate(gsubs + submits):
          print(f"RKProgram {self.name}: CPU-fallback fxn {si+1}/{len(gsubs)+len(submits)} -> clang ({len(src.splitlines())-2} lines)")
          print(src, end="")
      # each fallback is its own C function g0,g1,.../k0,k1,...; compiled together (one clang call) but dispatched separately
      self._lib = self._compile("\n".join(gsubs + submits))
      self._gemm_fxns = [self._lib[f"g{gi}"] for gi in range(len(gsubs))]
      self._fxns = [self._lib[f"k{si}"] for si in range(len(submits))]
  def _compile(self, src:str):
    import ctypes, subprocess, tempfile, os
    fd, so = tempfile.mkstemp(suffix=".so"); os.close(fd)
    subprocess.run([getenv("CC", "clang"), "-O0", "-shared", "-fPIC", "-x", "c", "-", "-lm", "-o", so],
                   input=src.encode(), check=True, stderr=subprocess.PIPE)
    return ctypes.CDLL(so)
  def __call__(self, *bufs, global_size=(1,1,1), local_size=(1,1,1), vals:tuple[int,...]=(), wait=False, **kw):
    import ctypes
    from tinygrad.helpers import mv_address
    with cpu_profile(self.name, self.device):
      if self.prog[0] == "chunks":                              # NPU GEMMs + EW, each falling back to its clang fxn on failure
        bufs = list(bufs)                                       # extend with SCRATCH buffers for NPU EW sub-DAG outputs (ids >= nreal)
        for sid in range(len(bufs), self._nbufs):
          d = next(s[1] for s in self.prog[1] if s[0] == "ew" and s[1]["out"][0] == sid)
          bufs.append(memoryview(bytearray(d["n"] * (2 if d["dt"] == "float16" else 4))))   # at the sub-DAG's float width (fp16/fp32)
        B = (ctypes.c_void_p*self._nbufs)(*[mv_address(bufs[i]) for i in range(self._nbufs)])
        for i, g in enumerate(self._npu_gemm):
          M, K, N, bufA, bufB, bufC, bias, plan = g[0], g[1], g[2], g[3], g[4], g[11], g[15], self._npu_gemm_cmd[i]
          try:                                                  # GEMM on the NPU MAC FIRST (renderer's command) -> writes C
            if plan is None: raise RuntimeError("no NPU GEMM command")
            if DEBUG >= 2: print(f"\033[35m*** RK NPU\033[0m  GEMM MAC M={M} K={K} N={N}  C[{g[12]}:] <- buf{bufA} @ buf{bufB}" +
                                 (f" + bias[{N}] (fused augment)" if isinstance(bias, tuple) else
                                  f" + {bias} (fused DPU bias)" if bias is not None else "") + "  (renderer cmd)")
            _run_npu_gemm(g, plan, bufs)
          except (OSError, RuntimeError) as e:                  # NPU submit failed (e.g. ENXIO) -> recompute the GEMM on CPU (clang)
            if DEBUG >= 2: print(f"\033[33m*** RK NPU GEMM failed ({e}) -> CPU clang fallback\033[0m")
            self._gemm_fxns[i](B)
        for i, sub in enumerate(self.prog[1]):                  # then each EW epilogue: NPU DPU-EW (chain_add) first, clang fallback
          if sub[0] == "ew":
            d = sub[1]
            try:                                                # submit the renderer's NPU command (d["npu"]); runtime only runs it
              if DEBUG >= 2: print(f"\033[35m*** RK NPU\033[0m  EW chain ({d['npu']['ntask']} op, {len(d['npu']['tiles'])} tile) " +
                                   f"n={d['n']} {d['dt']} -> buf{d['out'][0]}[{d['out'][1]}:]  (renderer cmd)")
              _run_npu_ew(d, bufs, self._ew_cache.setdefault(i, {}))
            except (OSError, RuntimeError) as e:                # NPU EW submit failed -> recompute the epilogue on CPU (clang)
              if DEBUG >= 2: print(f"\033[33m*** RK NPU EW failed ({e}) -> CPU clang fallback\033[0m")
              self._fxns[i](B)
          else: self._fxns[i](B)                                # cloop: clang only (no NPU path), reads any C written above
    return None

class RKAllocator(Allocator['RKDevice']):
  def _alloc(self, size, options): return memoryview(bytearray(size))
  def _copyin(self, dest, src:memoryview): dest[:] = src
  def _copyout(self, dest:memoryview, src): dest[:] = src

class RKDevice(Compiled):
  def __init__(self, device:str):
    renderers = [RKRenderer] + [r for m in [cstyle, nir, ptx, llvmir, wgsl] for r in m.__dict__.values()
                                if inspect.isclass(r) and issubclass(r, Renderer)]
    super().__init__(device, RKAllocator(self), dedup(renderers), functools.partial(RKProgram, device))
